### ISSUE TITLE
Continious Delivery

### ISSUE THREAD

**Issue by Baklap4** [performous/performous#214]
At my current job we work a lot with GitLab CI and some platforms to have Continious Delivery.
It'd be nice to set it up for Performous aswell.

I didn't look into it yet for Semaphore but i bet there'll be some options to do this.

# Branching strategy
I'd suggest the following branching stategy:
- `master` < for releases
- `staging` < for testing before release
- `feature/<name>` or `bug/<name>` < for adding or fixing stuff.

# Automation
1. Create Feature branch and push fixes/features to it.
2. Create merge request to staging
3. When Feature is ready merge if accepted by the community
4. On staging the CI will do the following steps:
    - Build for every platform (Windows, OSX, Linux)
    - Run unit tests (if we have any)
5. If step 4 succeeded continue with merge to master
6. Build once more now on Master. CI will follow the steps listed below:
    - Apply new (sub)version
    - Build for every platform (Windows, OSX, Linux)
    - Run unit tests (if we have any)
    - Create artifacts seperated for each platform
    - Deploy artifacts to somewhere people can download the latest build as zip (containing the build with executable) and the installer (which will install the latest build)

# Versioning
We need to figure this one out

# **Discuss**
@performous/contributors

**Comment by basisbit** [comment]
maybe this should be split into two issues?
- setting up a CI system (preferably Travis CI because it is deeply integrated into github (builds automagically for every new pull request or similar), nothing privately hosted and whoever is repository admin also is travis CI admin)
- switching to a branching strategy - this should be discussed somewhere.

**Comment by TobiX** [comment]
Since we already have CI with Semaphore (https://semaphoreci.com/performous/performous), the only thing missing for continuous "delivery" is to activate any of the deployment options there.

When I set that up, I decided against Travis-CI, because their base system is so awful old...

PS: We have daily Ubuntu packages: https://code.launchpad.net/~performous-team/+recipe/performous-daily

**Comment by Baklap4** [comment]
# TODO
- [ ] Set up mxe nightly builds @TobiX manages this when he finds some time
    - [ ] Building
    - [ ] Artifacts somewhere downloadable
- [ ] Set up mac nightly builds
    - [ ] Building
    - [ ] Artifacts somewhere downloadable
- [ ] Add Git branching strategy on wiki
- [x] Make Master branch protected + Review required on feature/hotfix branches thanks @nieknooijens 
- [x] Add Master build status to https://github.com/performous/performous/blob/master/README.md

**Comment by Baklap4** [comment]
Closing this issue in favor of #389
