### ISSUE TITLE
Discord as new communication channel

### ISSUE THREAD

**Issue by nieknooijens** [performous/performous#221]
I've set up a discord server as new comunication channel.
https://discord.gg/NS3m3ad

the reason for this is that discord saves the messages that came in, so I don't have to be online all the time (which I often forget) unlike IRC. also the IRC isn't really used anymore. This also allows me to better answer any questions that might come in. For now this will be an alternative that exists side-by-side next to the IRC.

**Comment by Baklap4** [comment]
Added the link to the readme as of: https://github.com/performous/performous/commit/b58952d62e5607ac6c23f95e79fa9dee7e5401c3.

This can be closed when https://github.com/performous/web/issues/5 is closed and when the irc-bridge bot is setup. @nieknooijens please check the discord general channel and reply to rainbowderpy.

**Comment by Baklap4** [comment]
https://github.com/performous/web/issues/5 is closed per: https://github.com/performous/web/commit/7c317ff0059a04e314cbbc2603b7349a70227853

**Comment by Baklap4** [comment]
# TODO
- [x] Added discord link to readme (see https://github.com/performous/performous/commit/b58952d62e5607ac6c23f95e79fa9dee7e5401c3)
- [x] https://github.com/performous/web/issues/5 (see https://github.com/performous/web/commit/7c317ff0059a04e314cbbc2603b7349a70227853 )
- [x] Setup bridge between discord and IRC
- [ ] Set up webhooks to inform about git push events (Related to #218 we need admin rights for hooks)
- [ ] Set up webhook to create/edit/close issues (Related to #218 we need admin rights for hooks)

**Comment by Baklap4** [comment]
@nieknooijens #218 is closed which means you can setup these hooks ^^

**Comment by nieknooijens** [comment]
@Baklap4 well there's a slight problem: we don't really need webhooks anymore.
think about it, commits and pushes are already pushed to IRC, which is bridged to discord, so it gets there already.

**Comment by Baklap4** [comment]
@nieknooijens Git commits/pushes indeed however issue handling aswell?
