### ISSUE TITLE
Stats page

### ISSUE THREAD

**Issue by Baklap4** [performous/performous#240]
I'm quite fond of numbers and such.
So i thought why not create a statistics page within the webserver?

# TODO 
- [ ] Stats endpoint (GET/POST)
- [ ] Save stats locally to persist stats over multiple sessions
- [ ] Read stats

# TODO Global stats
- [ ] Total of songs played since install
- [ ] Total of time sung since install
- [ ] Top 10 most requested songs
- [ ] All song history
- [ ] Record of longest playlist of all time

# TODO Stats since startup
- [ ] Show songhistory since startup
- [ ] Show count of songs that've been played since startup
- [ ] Show total time sung
- [ ] Show longest playlist time for that session

Any other cool stats to show to the enduser if you think of any add them to the list

**Comment by nieknooijens** [comment]
I also think we should add a bookkeeping menu in the UI itself and provide an on/off switch in the options menu. @Baklap4 will probably need this since he got a letter from the SABAM last week :laughing: if we're continuing this on events we probably need to be able to save a list of played songs during that event for the copyright authorities (yes it sucks, I know) to make it easier for the event organizers. 
this does bring up the question: when Is a song considered "finished" and should count for the bookkeeping? when it has played for 50% or when it has been played completely? performous has a "song_finished" state in screensing.cc to determine when to display the score window, we could use that as trigger for making a song "count" in the bookkeeping.

**Comment by Baklap4** [comment]
Nah i thought of this way earlier than the sabam thing ;) never issued it though :joy:. I think a song is finished when it's played for a full 100%.

**Comment by nieknooijens** [comment]
@Baklap4 full 100% or when the last sentence has finished? (when it says "press enter to display scores / autoplay enabled" I think the last option.

**Comment by Baklap4** [comment]
Yes when the last sentence has finished :)

**Comment by Baklap4** [comment]
Going to work on this by tonight
