### ISSUE TITLE
Add option to set in game language

### ISSUE THREAD

**Issue by Baklap4** [performous/performous#246]
As the title says, add an option (In game menu and xml) to set the in game language. Right now we have to do the following to launch performous in another language:
```
export LANG=nl_NL.UTF-8
export LANGUAGE=nl_NL
```
This is not user friendly :joy:

Referenced from #236 

# TODO:
- [x] Add menu item
- [x] Show only 100% translated languages??
    - [x] It defaults to English when there's no translation found. If objection please mention
- [x] Save it to config.xml
- [x] Load the language at runtime
- [x] ~~Include #242~~

**Comment by basisbit** [comment]
how about showing the english text when translation is missing? This also allows for easier modification and future development.

**Comment by nieknooijens** [comment]
@basisbit  doesn't it already do that?

**Comment by Baklap4** [comment]
It does indeed, if there's no translation it'll default to english :+1:

**Comment by Baklap4** [comment]
Does anyone have an idea how to switch languages during runtime? That's the only thing bothering me right now.. please see https://github.com/performous/performous/tree/feature/ChangeLocale for my current wip

**Comment by nieknooijens** [comment]
isn't there somewhere during startup where performous grabs the system locale? we could possibly just change that value.

**Comment by Baklap4** [comment]
well that's the funny thing.. There is: `TranslationEngine` which uses `boost::locale`
However if i let it generate the locale for [Dutch](https://github.com/performous/performous/blob/feature/ChangeLocale/game/i18n.hh#L59) it just won't show me in dutch :/

**Comment by nieknooijens** [comment]
worst case scenario we've hit a "feature" in boost::locale

**Comment by Baklap4** [comment]
PR is added to get this within performous! :D
It seems i already had it quite working however it seems when you locally test it (without installing) it won't make the directory structure as it would when you install the languages...
