### ISSUE TITLE
Change webserver.cc to RESTful-API

### ISSUE THREAD

**Issue by Baklap4** [performous/performous#252]
Currently the webserver isn't quite a rest-api.
I'd love to see this changed.

# TODO
- [ ]Change webserver.cc to a true REST-api
    - [ ] Use correct HTTP-statuscodes
    - [ ] Use a specified error model
    - [ ] Use a controller/action/{id}/{subviews} route model
    - [ ] All routes currently defined will have to be moved in the frontend.
- [ ] Update Api docs
- [ ] Add swagger UI under /api/docs within the webfrontend
- [ ] Authorization?
    - Yes i had once someone in the crowd who got my ip and added/deleted/prioritized stuff :-1: 
- [ ] Add `id` to song object which uniquely identifies it.
    - While reloading the database with still some songs in the playlist, change those id's to max.int - length of playlist to prevent id/pointer collision. 
    - These shared pointers will be automaticly removed once they have been played.

**Comment by Lord-Kamina** [comment]
Is there still anything here that isn't done @Baklap4 ?

**Comment by Baklap4** [comment]
None of it is done yet. I added this because of extensability of the webfrontend, you could even say theming. We basicly need to have proper documentation covering our endpoints so a frontend can be build just on top of that. I've made an attempt to document the endpoints here: https://github.com/performous/performous/wiki/Webserver-API

**Comment by xoellijo** [comment]
I was going to open a Feature request practically identical to this one.

I've seen the API proposal. It seems very focused on managing the song database. But I'm missing a few things:
For example, user roles (querying, so users can see the list of available songs and even click to "suggest" songs). And another set of administrative controls, to manage the playlist, and these other things:

1. Player management (with username and microphone assignment). Add, remove, modify...
2. Playback management: start, stop, and status check (knowing which song is playing and how much time is left).

**Comment by Lord-Kamina** [comment]
We have at least two open webserver overhaul PRs, which are not quite mergeable at the moment due to conflicts. 

I'm of course partial to myself's, based on RESTinio
