### ISSUE TITLE
webserver annoyances

### ISSUE THREAD

**Issue by nieknooijens** [performous/performous#293]
while the new webserver is pretty fast and snappy I did encounter some minor annoyances using it last weekend @tomofair nijmegen.

first of all the Enter button behaviour is not what it's supposed to be, instead of doing the same as pressing "search"it selects the first entry of autocomplete, forcing you to press "search" with your mouse.
which brings me to the second issue: clicking an entry in the autocomplete list quite often fails. sometimes it works, but most often it fails with a message "no songs found using current filter".

it's not game-breaking, but it can become quite annoying when having to add a bunch of songs at once.

**Comment by Baklap4** [comment]
Also linked by #290

**Comment by Baklap4** [comment]
# TODO's
- [ ] Fix enter keypress on searching to actually search instead of selecting first autocomplete option
- [ ] Fix clicking autocomplete suggestions: 'No songs found using current filter'
- [ ] Fix #290 Probs related to 2nd TODO item

**Comment by Baklap4** [comment]
Fix commited as per #317
