### ISSUE TITLE
Using C++11 facilities to clean up code and Boost dependencies

### ISSUE THREAD

**Issue by Tronic** [performous/performous#39]
We can reduce but not entirely remove dependency on Boost by replacing parts of it with stdlib equivalents. This bug is a tracker for features to replace, and for discussion about compiler compatibility.

- [ ] boost/algorithm/string.hpp: No stdlib equivalents
- [ ] boost/bind.hpp: std::bind in functional
- [ ] boost/circular_buffer.hpp: No stdlib equivalent
- [ ] boost/cstdint.hpp: Now in stdlib (cstdint)
- [ ] boost/date_time.hpp: Partial support from stdlib (chrono)
- [ ] boost/filesystem.hpp: C++ still doesn't know of files :/
- [ ] boost/foreach.hpp: C++11 built-in range-based for!
- [ ] boost/format.hpp: No direct stdlib equivalent but see std::to_string(num)
- [ ] boost/function.hpp: std::function (functional)
- [ ] boost/iostreams/stream_buffer.hpp: ???
- [ ] boost/lexical_cast.hpp: See std::to_string and std::stoi etc. (string)
- [ ] boost/noncopyable.hpp: C++11 deleted functions (but noncopyable is cleaner in code)
- [ ] boost/program_options.hpp: Never gonna get into stdlib
- [ ] boost/ptr_container/: Not in C++11 and probably not in C++14 either.
- [ ] boost/regex.hpp: The last time I tried (quite recently), the libstdc++ implementation was unusably incomplete.
- [ ] boost/smart_ptr/scoped_ptr.hpp: std::unique_ptr in memory (also replaces std::auto_ptr)
- [ ] boost/smart_ptr/shared_ptr.hpp: std::unique_ptr (if shared_ptr was only used for calling a free function of a C lib), std::shared_ptr if the resource is actually shared, C++11 move semantics instead if a resourse is only being moved.
- [ ] boost/thread/: std::thread and stdlib mutexes (no idea if stdlib implementation is good yet or if all necessary lock types are included or not)
- [ ] boost/variant.hpp: Didn't make it into C++11

We don't currently use Boost.ASIO directly but likely will, soon. Sockets didn't make it into C++11.

**Comment by zosrothko** [comment]
If you need a lightweight c++ library to replace part or whole Boost, look at  [Poco](https://pocoproject.org/)

**Comment by Baklap4** [comment]
slowly we're getting there: https://github.com/performous/performous/pull/339

**Comment by Baklap4** [comment]
Slowly getting there by replacing boost::shared_ptrs and boost::thread -> std::thread: #347

**Comment by Baklap4** [comment]
Used @Tronic 's list of items to check of the items we have done already to get a more detailed status into this cleanup session:

- [ ] boost/algorithm/string.hpp: No stdlib equivalents
- [ ] boost/bind.hpp: std::bind in functional
- [ ] boost/circular_buffer.hpp: No stdlib equivalent
- [ ] boost/cstdint.hpp: Now in stdlib (cstdint)
- [ ] boost/date_time.hpp: Partial support from stdlib (chrono)
- [ ] boost/filesystem.hpp: C++ still doesn't know of files :/
- [ ] boost/foreach.hpp: C++11 built-in range-based for!
- [ ] boost/format.hpp: No direct stdlib equivalent but see std::to_string(num)
- [ ] boost/function.hpp: std::function (functional)
- [ ] boost/iostreams/stream_buffer.hpp: ???
- [ ] boost/lexical_cast.hpp: See std::to_string and std::stoi etc. (string)
- [ ] boost/noncopyable.hpp: C++11 deleted functions (but noncopyable is cleaner in code)
- [ ] boost/program_options.hpp: Never gonna get into stdlib
- [ ] boost/ptr_container/: Not in C++11 and probably not in C++14 either.
- [ ] boost/regex.hpp: The last time I tried (quite recently), the libstdc++ implementation was unusably incomplete.
- [ ] boost/smart_ptr/scoped_ptr.hpp: std::unique_ptr in memory (also replaces std::auto_ptr)
- [ ] boost/smart_ptr/shared_ptr.hpp: std::unique_ptr (if shared_ptr was only used for calling a free function of a C lib), std::shared_ptr if the resource is actually shared, C++11 move semantics instead if a resourse is only being moved.
- [ ] boost/thread/: std::thread and stdlib mutexes (no idea if stdlib implementation is good yet or if all necessary lock types are included or not)
- [ ] boost/variant.hpp: Didn't make it into C++11

**Comment by Lord-Kamina** [comment]
I replaced some boost::function calls with the std version in my GL branch. Also, ptr_container is not really needed anymore because now stl containers can contain smart pointers (at least one instance of which I also fixed in the GL branch, see ShaderMap)

**Comment by Baklap4** [comment]
@Lord-Kamina please cross off what you think is already fixed i'm currently checking master upon these

**Comment by Lord-Kamina** [comment]
Also, correct me if I'm wrong but we're actually targetting c++14 now. No?

**Comment by Lord-Kamina** [comment]
BTW. Here's the specific relevant commit you can use as a base if you want to tackle the remaining ptr_map and ptr_vectors. If not I'll do them tomorrow. 

https://github.com/performous/performous/commit/c234b7934d67b4e01ca35ea7e0a2ac17310cb863

**Comment by Baklap4** [comment]
Thanks it's not all ptr_maps and vectors though. I'm atm busy with tackling the cachemap. I fixed all the ptr_vectors already

**Comment by Baklap4** [comment]
@Lord-Kamina some weird stuff happens if i cherry-pick that specific commit within audio.cc hmmm

**Comment by Lord-Kamina** [comment]
Yeah; don't. I just linked it to show an example of how I solved it. Have you had time to finish checking that PR?

**Comment by Baklap4** [comment]
# TODO
- [ ] `boost/format.hpp` can be replaced with the much faster: [fmtlib/fmt](https://github.com/fmtlib/fmt)
- [ ] `boost/iostreams/stream_buffer.hpp` can be replaced with `std::fstream` since we don't do fancy stuff with the streams. So this is basicly a lot of bloat for a simple read stream command.
- [ ] `boost/algorithm/string.hpp` can probably be replaced with stl functionality as it's just manipulating strings.

**Comment by Tronic** [comment]
There is also https://en.cppreference.com/w/cpp/utility/format/format

**Comment by Tronic** [comment]
As for iostreams, those should be avoided as far as possibly at least with song loading and other such things where performance matters. C++ iostreams are horribly bad in all respects, and unfortunately also **slow**.

**Comment by Baklap4** [comment]
As @yoda-jm pointed out there's still lots of boost stuff left:
https://github.com/performous/performous/pull/714#issuecomment-1101387585
> Here is the list of stuff we should try to remove:
>$ git grep boost | grep include | cut -d: -f2- | sort | uniq
#include <boost/algorithm/string/case_conv.hpp>
#include <boost/algorithm/string/classification.hpp>
#include <boost/algorithm/string.hpp>
#include <boost/algorithm/string/replace.hpp>
#include <boost/asio.hpp>
#include <boost/filesystem.hpp>
#include <boost/format.hpp>
#include <boost/iostreams/device/file_descriptor.hpp>
#include <boost/iostreams/stream.hpp>
#include <boost/locale.hpp>
#include <boost/predef/os.h>
#include <boost/program_options.hpp>
#include <boost/range/adaptor/reversed.hpp>
#include <boost/range.hpp>
#include <boost/range/iterator_range.hpp>

Some of them are optional like boost/asio (webserver get ip) and boost/filesystem ("hack" for a platform since they didn't support std::filesystem yet i think?)

**Comment by twollgam** [comment]
boost::filesystem is only used on Apple. Is this still needed? @Baklap4 @Lord-Kamina 

Else we could remove it.

**Comment by Lord-Kamina** [comment]
Ish. It's required previous to 10.15. I guess it IS a pretty old OS by this point.

**Comment by Baklap4** [comment]
Let's remove it. 

MacOS 10.15 is already out of support

![image](https://github.com/performous/performous/assets/3918517/e4096382-0d02-4d8a-986d-a1759201fe49)

**Comment by Baklap4** [comment]
@twollgam i think we still need boost for the program options right? (std doesn't come with a nice way to do this, not that we have anything fancy though...)
Can you make a pr to remove the other dependencies you've eliminated in the other 3 pr's?

**Comment by twollgam** [comment]
Oh yes. You are right. No I have no good idea how to replace it.

I will make the new pr if the others are merged. 👍
