### ISSUE TITLE
Shortcut list should be part of the game

### ISSUE THREAD

**Issue by jose1711** [performous/performous#456]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

All game shortcuts are described nicely at https://github.com/performous/performous/wiki/Keys. Having an option to see a shortened version after pressing F1 would be useful to
* new performous users
* users running performous offline

**Comment by Baklap4** [comment]
It would be nice to provide a helpers section indeed, thanks for the suggestion!

**Comment by Baklap4** [comment]
@ooshlablu can you verify if installing performous the keys are mentioned within the manpages?

**Comment by Baklap4** [comment]
### Todo

- [ ] Add info to the manpages
- [ ] Add an in game section to show all shortcuts as mentioned on the wiki.
    - [ ] If possible generated from usage from our code

**Comment by ooshlablu** [comment]
Most of the content from that wiki page is missing in the Performous man page.

**Comment by Baklap4** [comment]
seems we've got some work to do 😂
