### ISSUE TITLE
Windows native build runtime issues

### ISSUE THREAD

**Issue by Baklap4** [performous/performous#632]
### Do you want to request a *feature* or report a *bug*?

Bug/issues

### Description

This will list all runtime bugs and issues using visual studio and native builds.
So this can be picked at a later time.

### List

- [x] Menu -> Paths -> NULL reference exception. `getenv("HOME")` returns NULL on windows (fix commited #650)
- [x] Audio Devices -> Selected audio device is not remembered (but still in use and works) (fix commited in #655)
- [x] ~~Audio -> Every sample rate above 48.000 Hz is not working with a result "sample rate error" + no sound~~ (#417)
- [x] Webcam background -> Auto detect (webcam Id = -1) doesn't work as of yet. Setting this to 0 is the current workaround. (fix committed #652 )
    - [x] Auto detect was wrongly implemented by us. Autodetect has been `0` for already 11 years. So that's just a bug.
- [x] Duet songs didn't play on Windows. (fix commited #650)

### Build issues

- [x] Webserver support currently unavailable (fix commited #712)
- [x] LibRSVG -> d suffix (debug) _LIBRARY cannot be found
- [x] LibSDL2 -> d suffix (debug) sdl2d.dll doesn't get copied over after build
- [x] LibXML2 -> Library cannot be found.
- [ ] Optional: Pkgconfig -> ideally we'd like to be able to compile without pkgconfig.

**Comment by Baklap4** [comment]
SDL2 still has troubles when building locally with vcpkg.

Within Debug mode i'd expect to get sdl2d.dll however it's linking to sdl2.dll and then when trying to run expects sdl2.dll to be there but isn't which results into a runtime error crashing the game.

@yoda-jm @OznOg Any trouble with this on linux side / any idea for a solution to this?
