### ISSUE TITLE
Save Webcam video feed to file

### ISSUE THREAD

**Issue by Baklap4** [performous/performous#633]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

There's a cmake flag `SAVE_WEBCAM_VIDEO` introduced [way back here](https://github.com/performous/performous/commit/25a9da624497f21e57032f086275670647e208d1). 
It's currently undocumented and would be nice to be able to toggle this from within the game settings menu.

### Todo

- [ ] Remove flag
- [ ] Add option to the menu
- [ ] Based on configuration save the webcam video

### Acceptance

- [ ] Video gets saved to file
- [ ] Created video can be replayed from vlcplayer

**Comment by Baklap4** [comment]
Soo let's see `SAVE_WEBCAM_VIDEO` ifdef is used as experimental "save webcam feed" support. It works quite alright after it was patched with some minor changes. It only saves the video under the same name. So starting a new song will overwrite the current one (not quite handy). It also doesn't mix in the mp3 and the vocals itself so it's just a muted mpeg1 video. It was probably just started with and never really finished.

Depending on the outcome of #638 stuff will be done
