### ISSUE TITLE
Difficulty per song instead of globally through settings

### ISSUE THREAD

**Issue by Baklap4** [performous/performous#654]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Currently within the menu you can change your sing difficulty.
It'd be nice to be able to set this per song before playing the song. 
This should only be the case when autoplay is not enabled. As else that would interupt the flow of autoplay.

Referenced from #570 

### Todo

- [ ] Implement difficulty per song but only if autoplay is not enabled.
- [ ] Remove the global difficulty from the settings.
- [ ] Add an intuitive way to change difficulty for the song
    - [ ] Can be done like the way a duet song is played.
