### ISSUE TITLE
Nsis installer make use of components

### ISSUE THREAD

**Issue by Baklap4** [performous/performous#658]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Within nsis we can specify components to be installed with and alongside performous.
This can be configured using `cpack`. 
Within the installer you can then check what components you want to install.

Some components i can think of are (if there are more let me know in the comments):

- Webserver
- Webcam
- Midi I/O

The layout would be:
```
Performous
    |___> Webserver
    |___> Webcam
    |___> Midi I/O
```

Example picture:
![image](https://user-images.githubusercontent.com/3918517/129939361-9e0c1f0b-c300-47ef-b044-29e21b063b18.png)

### Todo

- [ ] Figure out components in [cpack](https://gitlab.kitware.com/cmake/community/-/wikis/doc/cpack/Component-Install-With-CPack)
- [ ] Make an optional component for the webserver
    - [ ] No cpprest dll's will be installed
- [ ] Make an optional component for PortMidi
    - [ ] No portmidi dll's will be installed
- [ ] Make an optional component for Webcam
    - [ ] No opencv dll's will be installed

**Comment by Baklap4** [comment]
Install all languages or just the ones you want

**Comment by Baklap4** [comment]
I've created a small demo for this. What are your thoughts?

The languages is collapsed since it lists all of our languages which is a pretty big list.
It currently looks like this:
![image](https://user-images.githubusercontent.com/3918517/131750209-8be135e0-ee6b-47e5-b7af-f871ead672df.png)

**Comment by Baklap4** [comment]
Closing this for the reasons above: there's no real usecase for this, yet.
