### ISSUE TITLE
Performous Auto-updater

### ISSUE THREAD

**Issue by Baklap4** [performous/performous#678]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Performous to come with an auto-update functionality.

### Motivation for this

After the upcoming 'big' release we'd like to release more often. Therefore it's good practice to have some kind of auto-updater available.

This updater will check the current installed version against the latest here on github. If it's not equal to eachother prompt the user that there is an update available.

### Todo list

- [ ] Check for new version while starting up. (Can be done while loading everything)
- [ ] If there is a newer version: Download new version
- [ ] Update to the new version
- [ ] Show a small list of changes in game after update
- [ ] Config setting to disable auto update. Default we will auto-update
- [ ] Config setting to opt in for beta-releases. Default will be off

**Comment by Baklap4** [comment]
I guess we can use the github api to give us the latest release artefacts -> https://api.github.com/repos/performous/performous/releases/latest

**Comment by Baklap4** [comment]
Currently the daily build apt-repo isn't up-to-date and lists performous 1.1

**Comment by Baklap4** [comment]
So to resume what's been said in discord:
- Linux uses a package manager, all updates should come from there
    - We have a nightly build PPA but that's only for ubuntu + it hasn't been updated since 1.1
    - I'm currently talking with Packagecloud which supports:
        - deb packages
        - rpm packages
        - Note: The GH-Action from packagecloud only supports deb packages i think
- Windows & Mac would benefit from an auto-updater as described in this issue
